main: com.benoolean.KitWar.KitWar
name: KitWar
version: 1.0
author: benoolean
api-version: 1.16
description: Minigame night!

commands:
  team:
    description: Choose a team!
  kit:
    description: Selecting a kit and claim victory for your team!